### ISSUE TITLE
Issue with API 17

### ISSUE THREAD

**Issue by yassine987** [codemybrainsout/ahoy-onboarding#2]
I use your Library in 2 different projects, it's work perfectly on my **Samsung SM-J200F (Android 5.1.1, API 22)**, but unfortunately, didn't look good on my **Samsung GT-S7580 (Android 4.2.2 API 17)** , the Image, Title, Subtitle are in the same place ( middle of AhoyOnboarderCard), and the background Color change from the first gradient to white, after while change to the first gradient again.
![device-2016-09-25-012733](https://cloud.githubusercontent.com/assets/17654524/18812053/5af9bd3c-82bf-11e6-90db-71968952991c.png)
![device-2016-09-25-012810](https://cloud.githubusercontent.com/assets/17654524/18812054/5b05bc4a-82bf-11e6-88e8-4d7cc3c4bab0.png)

**Comment by wax911** [comment]
@yassine987 I've also noticed the same issues, I had to edit the source to set the correct paddings and positions with some items, I also made a pull request with some of the fixes including a landscape orientation fix. Just waiting till it gets approved, the issue also seems to occur on devices with a smaller resolution and even on API 19 (LG G3)

**Comment by codemybrainsout** [comment]
@wax911 Thanks for your contribution. I've reviewed your changes and added it to the master branch. The Landscape layout looks neat. Feel free to add more features to this repository in future.

**Comment by codemybrainsout** [comment]
@yassine987 Include the latest version of the library in your project.

`compile 'com.codemybrainsout.onboarding:onboarder:1.0.1'` 

Please report if the problem still persists.

**Comment by wax911** [comment]
@codemybrainsout Thanks 👍 I'll be sure to add more things as I go along!

**Comment by wax911** [comment]
@codemybrainsout I've add some new features in the pull request. Check them out and tell me what you think, just ignore some of the reverted changes from git. @yassine987 could you check if the issue is still present when codemybrains updates the library?

**Comment by codemybrainsout** [comment]
@yassine987 @wax911 I've updated the project to v1.0.2. Update the dependency to the latest version.

`compile 'com.codemybrainsout.onboarding:onboarder:1.0.2'`

**Comment by vik17ag** [comment]
Hi @codemybrainsout , I tried your latest  compile 'com.codemybrainsout.onboarding:onboarder:1.0.2'
, the padding is slightly improved. But still, text and image overlapping occurs in low re devices - ex : Nexus S API 23 emulator. 
Could you correct it? Thanks

**Comment by wax911** [comment]
@vik17ag can you post a screenshot here, I might be able to help, on the previous release I did try to improve the layout with smaller display sizes but I couldn't really test due to the missing resources (more android devices)
