### ISSUE TITLE
Changing image size

### ISSUE THREAD

**Issue by GauravCreed** [codemybrainsout/ahoy-onboarding#5]
Hi @wax911 

thanks for giving wonderful library, 

i have a small problem to just increase the size of image which is display in a center of the screen, is it possible?

if yes then please help me.

Thanks . (_)

**Comment by wax911** [comment]
Hi @GauravCreed credits actually belong to @codemybrainsout he/she is the one that made the library and yes it is possible to increase the size of the image, I'll try and see if I can set some parameters to do that later on today 👍

**Comment by GauravCreed** [comment]
@wax911 

Okay , Not an issue.
thanks.

**Comment by wax911** [comment]
@GauravCreed Sorry for not looking into this as of yet, I've been super occupied with work e.t.c I'll try to set some time aside tomorrow. I've been thinking would it be easier to have a method such as set image size and you give it a resource item? the resource it might have the different dimens for the image in different screen sizes?

**Comment by GauravCreed** [comment]
@wax911 not a problem to late response.

what i want  from you .

1.    Your  library is perfect for me, i just want to increase the size of images which is displayed in app introduction, and if i want more from u to that can i  hide the description of app, i want only title and images nothing else. so the images can show bigger from previous, i saw u a UI like tthis

reference link : https://android-arsenal.com/details/1/3322 

it's request to please give me solution as soon as faster.

Thanks

**Comment by codemybrainsout** [comment]
@GauravCreed Compile using the latest version of the project 
```compile 'com.codemybrainsout.onboarding:onboarder:1.0.3'``` and use 
```.setIconLayoutParams(iconWidth, iconHeight, marginTop, marginLeft, marginRight, marginBottom);``` for changing the image size and margins.
