### ISSUE TITLE
Looks great but how can I display this?

### ISSUE THREAD

**Issue by AviadKlein10** [codemybrainsout/ahoy-onboarding#6]
Hi thank you for the library looks awsome!
But you didn't wrote how to start this

thank you

**Comment by ujwalp15** [comment]
Yeah, same question

**Comment by gaurigadkari** [comment]
Same here

**Comment by snotyak** [comment]
`context.startActivity(new Intent(context, YourActivity.class));`

**Comment by ahulr** [comment]
Hi,
As mentioned in the Readme under "How to use", extend your activity from
```public class YourActivity extends AhoyOnboarderActivity {```

Take a look at this activity from the sample app, if you're facing any issues while integrating this library.
https://github.com/codemybrainsout/ahoy-onboarding/blob/master/app/src/main/java/com/codemybrainsout/onboarding/GradientBackgroundExampleActivity.java
