### ISSUE TITLE
How can i increase width and height of image?

### ISSUE THREAD

**Issue by amankumarjain** [codemybrainsout/ahoy-onboarding#9]

**Comment by nicks258** [comment]
do you find any solution for that?

**Comment by amankumarjain** [comment]
not yet, but i will try to get into library to solve it

**Comment by ahulr** [comment]
If you're talking about the icon, use this - 
```ahoyOnboarderCard1.setIconLayoutParams(iconWidth, iconHeight, marginTop, marginLeft, marginRight, marginBottom);```
